### ISSUE TITLE
Crash in update dataset 

### ISSUE THREAD

**Issue by jheeffer** [Gapminder/waffle-server-import-cli#4]
Platform: Windows 10

Steps can be seen in log below:

```
C:\Users\Jasper>ws-cli
? Waffle Server Endpoint Select from the List
? Select Waffle Server Endpoint waffle-server-dev.gapminderdev.org (https://waffle-server-dev.gapminderdev.org)
? Authentication, Login dev@gapminder.org
? Authentication, Password ***********
? Choose Flow Default DataSet
? Choose Default DataSet Back
? Choose Flow Update DataSet
? List of DataSet Repositories (github.com) git@github.com:open-numbers/ddf--gapminder--systema_globalis.git


C:\Users\Jasper\AppData\Roaming\npm\node_modules\waffle-server-import-cli\service\git-flow.js:87
      let commitsList = commits.map(function(item){
                               ^

TypeError: Cannot read property 'map' of undefined
    at C:\Users\Jasper\AppData\Roaming\npm\node_modules\waffle-server-import-cli\service\git-flow.js:87:32
    at Git.<anonymous> (C:\Users\Jasper\AppData\Roaming\npm\node_modules\waffle-server-import-cli\node_modules\simple-git\src\git.js:833:21)
    at Git.<anonymous> (C:\Users\Jasper\AppData\Roaming\npm\node_modules\waffle-server-import-cli\node_modules\simple-git\src\git.js:990:21)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by vvpanchenko** [comment]
We have investigated this problem with @jheeffer . Readme file should be updated for Windows users
